name: medicinal_plant_flutter
description: "A Flutter app for medicinal plant classification using TensorFlow Lite."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image_picker: ^1.0.0
  camera: ^0.10.5
  permission_handler: ^11.0.0
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/test_images/Aloe_barbadensis_miller/
    - assets/test_images/Azadirachta_indica/
    - assets/test_images/Calotropis_gigantea/
    - assets/test_images/Centella_asiatica/
    - assets/test_images/Hibiscus_rosa_sinensis/
    - assets/test_images/Justicia_adhatoda/
    - assets/test_images/Kalanchoe_pinnata/
    - assets/test_images/Mentha_arvensis/
    - assets/test_images/Mikania_micrantha/
    - assets/test_images/Moringa_oleifera/
