// Plant asset image paths - organized for easy access
class PlantAssets {
  static const String basePath = 'assets/test_images';

  // Plant names (match model labels)
  static const List<String> plantNames = [    'Aloe_barbadensis_miller',
    'Azadirachta_indica',
    'Calotropis_gigantea',
    'Centella_asiatica',
    'Hibiscus_rosa_sinensis',
    'Justicia_adhatoda',
    'Kalanchoe_pinnata',
    'Mentha_arvensis',
    'Mikania_micrantha',
    'Moringa_oleifera',
  ];

  // Display names (user-friendly)
  static const Map<String, String> displayNames = {    'Aloe_barbadensis_miller': 'Aloe',
    'Azadirachta_indica': 'Neem',
    'Calotropis_gigantea': 'Ashoka',
    'Centella_asiatica': 'Centella',
    'Hibiscus_rosa_sinensis': 'Hibiscus',
    'Justicia_adhatoda': 'Justicia',
    'Kalanchoe_pinnata': 'Kalanchoe',
    'Mentha_arvensis': 'Mint',
    'Mikania_micrantha': 'Mikania',
    'Moringa_oleifera': 'Moringa',
  };

  static const Map<String, List<String>> images = {    'Aloe_barbadensis_miller': [
      'assets/test_images/Aloe_barbadensis_miller/100.jpg',
      'assets/test_images/Aloe_barbadensis_miller/102.jpg',
      'assets/test_images/Aloe_barbadensis_miller/140.jpg',
      'assets/test_images/Aloe_barbadensis_miller/142.jpg',
      'assets/test_images/Aloe_barbadensis_miller/144.jpg',
      'assets/test_images/Aloe_barbadensis_miller/176.jpg',
      'assets/test_images/Aloe_barbadensis_miller/178.jpg',
      'assets/test_images/Aloe_barbadensis_miller/208.jpg',
      'assets/test_images/Aloe_barbadensis_miller/210.jpg',
      'assets/test_images/Aloe_barbadensis_miller/218.jpg',
      'assets/test_images/Aloe_barbadensis_miller/22.jpg',
      'assets/test_images/Aloe_barbadensis_miller/220.jpg',
      'assets/test_images/Aloe_barbadensis_miller/222.jpg',
      'assets/test_images/Aloe_barbadensis_miller/24.jpg',
      'assets/test_images/Aloe_barbadensis_miller/278.jpg',
      'assets/test_images/Aloe_barbadensis_miller/304.jpg',
      'assets/test_images/Aloe_barbadensis_miller/306.jpg',
      'assets/test_images/Aloe_barbadensis_miller/318.jpg',
      'assets/test_images/Aloe_barbadensis_miller/326126.jpg',
      'assets/test_images/Aloe_barbadensis_miller/336.jpg',
      'assets/test_images/Aloe_barbadensis_miller/346.jpg',
      'assets/test_images/Aloe_barbadensis_miller/6.jpg',
      'assets/test_images/Aloe_barbadensis_miller/processed_img_Healthy11751.png',
      'assets/test_images/Aloe_barbadensis_miller/processed_img_Healthy11752.png',
      'assets/test_images/Aloe_barbadensis_miller/processed_img_Healthy11753.png',
      'assets/test_images/Aloe_barbadensis_miller/processed_img_Healthy11756.png',
      'assets/test_images/Aloe_barbadensis_miller/processed_img_Healthy11757.png',
      'assets/test_images/Aloe_barbadensis_miller/processed_img_Healthy11758.png',
      'assets/test_images/Aloe_barbadensis_miller/processed_img_Healthy11761.png',
      'assets/test_images/Aloe_barbadensis_miller/processed_img_Healthy11762.png',
      'assets/test_images/Aloe_barbadensis_miller/processed_img_Healthy11763.png',
      'assets/test_images/Aloe_barbadensis_miller/processed_img_Healthy11766.png',
      'assets/test_images/Aloe_barbadensis_miller/processed_img_Healthy11767.png',
      'assets/test_images/Aloe_barbadensis_miller/processed_img_Healthy11768.png',
    ],
    'Azadirachta_indica': [
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_8513.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_8543.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_8547.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_8563.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_8573.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_8630.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_8719.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_8849.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9036.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9071.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9073.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9081.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9164.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9166.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9174.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9207.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9217.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9287.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9333.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9338.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9545.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9559.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9633.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9677.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9711.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9733.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9772.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9777.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9960.JPG',
      'assets/test_images/Azadirachta_indica/Azadirachta_indica_0_9985.JPG',
    ],
    'Calotropis_gigantea': [
      'assets/test_images/Calotropis_gigantea/404.jpg',
      'assets/test_images/Calotropis_gigantea/406.jpg',
      'assets/test_images/Calotropis_gigantea/442.jpg',
      'assets/test_images/Calotropis_gigantea/444.jpg',
      'assets/test_images/Calotropis_gigantea/450.jpg',
      'assets/test_images/Calotropis_gigantea/452.jpg',
      'assets/test_images/Calotropis_gigantea/454.jpg',
      'assets/test_images/Calotropis_gigantea/466.jpg',
      'assets/test_images/Calotropis_gigantea/468.jpg',
      'assets/test_images/Calotropis_gigantea/474.jpg',
      'assets/test_images/Calotropis_gigantea/480.jpg',
      'assets/test_images/Calotropis_gigantea/484.jpg',
      'assets/test_images/Calotropis_gigantea/496.jpg',
      'assets/test_images/Calotropis_gigantea/498.jpg',
      'assets/test_images/Calotropis_gigantea/556.jpg',
      'assets/test_images/Calotropis_gigantea/558.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9179.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9180.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9181.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9182.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9183.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9184.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9185.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9186.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9187.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9188.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9189.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9190.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9191.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9193.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9194.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9195.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9196.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9201.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9202.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9203.jpg',
      'assets/test_images/Calotropis_gigantea/IMG_9204.jpg',
    ],
    'Centella_asiatica': [
      'assets/test_images/Centella_asiatica/4027.jpg',
      'assets/test_images/Centella_asiatica/4028.jpg',
      'assets/test_images/Centella_asiatica/4029.jpg',
      'assets/test_images/Centella_asiatica/4030.jpg',
      'assets/test_images/Centella_asiatica/4031.jpg',
      'assets/test_images/Centella_asiatica/4032.jpg',
      'assets/test_images/Centella_asiatica/4033.jpg',
      'assets/test_images/Centella_asiatica/4034.jpg',
      'assets/test_images/Centella_asiatica/5048.jpg',
      'assets/test_images/Centella_asiatica/5049.jpg',
      'assets/test_images/Centella_asiatica/5050.jpg',
      'assets/test_images/Centella_asiatica/5051.jpg',
      'assets/test_images/Centella_asiatica/5052.jpg',
      'assets/test_images/Centella_asiatica/5053.jpg',
      'assets/test_images/Centella_asiatica/5054.jpg',
      'assets/test_images/Centella_asiatica/IMG_0667.jpg',
      'assets/test_images/Centella_asiatica/IMG_0669.jpg',
      'assets/test_images/Centella_asiatica/IMG_0671.jpg',
      'assets/test_images/Centella_asiatica/IMG_0673.jpg',
      'assets/test_images/Centella_asiatica/IMG_0674.jpg',
      'assets/test_images/Centella_asiatica/IMG_0675.jpg',
      'assets/test_images/Centella_asiatica/IMG_0676.jpg',
      'assets/test_images/Centella_asiatica/IMG_0677.jpg',
      'assets/test_images/Centella_asiatica/IMG_4425.jpg',
      'assets/test_images/Centella_asiatica/IMG_4426.jpg',
      'assets/test_images/Centella_asiatica/IMG_4427.jpg',
      'assets/test_images/Centella_asiatica/IMG_4428.jpg',
      'assets/test_images/Centella_asiatica/IMG_4429.jpg',
      'assets/test_images/Centella_asiatica/IMG_4430.jpg',
      'assets/test_images/Centella_asiatica/IMG_4431.jpg',
      'assets/test_images/Centella_asiatica/IMG_4432.jpg',
      'assets/test_images/Centella_asiatica/IMG_4478.jpg',
      'assets/test_images/Centella_asiatica/IMG_4479.jpg',
      'assets/test_images/Centella_asiatica/IMG_4480.jpg',
      'assets/test_images/Centella_asiatica/IMG_4482.jpg',
    ],
    'Hibiscus_rosa_sinensis': [
      'assets/test_images/Hibiscus_rosa_sinensis/Hibiscus (266).jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/Hibiscus (267).jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/Hibiscus (268).jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/Hibiscus (269).jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/Hibiscus (270).jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/HR-S-039.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/HR-S-040.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/HR-S-041.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/HR-S-042.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/HR-S-043.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8663.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8665.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8667.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8668.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8669.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8670.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8671.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8672.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8673.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8676.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8677.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8678.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8757.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8758.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8759.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8760.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8761.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8762.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8763.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8764.jpg',
      'assets/test_images/Hibiscus_rosa_sinensis/IMG_8765.jpg',
    ],
    'Justicia_adhatoda': [
      'assets/test_images/Justicia_adhatoda/0096_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0097_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0098_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0099_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0100_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0101_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0102_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0103_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0104_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0105_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0106_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0108_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0109_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0110_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0111_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0112_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0113_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0114_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0115_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0116_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/0117_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/1001_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/1002_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/1008_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/1012_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/1014_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/1016_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/1017_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/20016_Justicia_adhatoda.JPG',
      'assets/test_images/Justicia_adhatoda/20057_Justicia_adhatoda.JPG',
    ],
    'Kalanchoe_pinnata': [
      'assets/test_images/Kalanchoe_pinnata/IMG_1117.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1118.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1120.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1122.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1123.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1124.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1125.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1126.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1127.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1130.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1131.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1132.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1188.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1189.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1190.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1192.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1193.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1194.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1195.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1208.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1210.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1211.jpg',
      'assets/test_images/Kalanchoe_pinnata/IMG_1212.jpg',
    ],
    'Mentha_arvensis': [
      'assets/test_images/Mentha_arvensis/121_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/122_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/123_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/124_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/125_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/126_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/127_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/128_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/129_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/130_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/131_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/132_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/133_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/134_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/135_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/136_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/137_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/138_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/139_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/140_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/141_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/142_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/143_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/144_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/145_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/146_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/147_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/148_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/149_Mentha_arvensis.jpg',
      'assets/test_images/Mentha_arvensis/150_Mentha_arvensis.jpg',
    ],
    'Mikania_micrantha': [
      'assets/test_images/Mikania_micrantha/IMG_0802.jpg',
      'assets/test_images/Mikania_micrantha/IMG_0803.jpg',
      'assets/test_images/Mikania_micrantha/IMG_0804.jpg',
      'assets/test_images/Mikania_micrantha/IMG_0805.jpg',
      'assets/test_images/Mikania_micrantha/IMG_0806.jpg',
      'assets/test_images/Mikania_micrantha/IMG_0807.jpg',
      'assets/test_images/Mikania_micrantha/IMG_0809.jpg',
      'assets/test_images/Mikania_micrantha/IMG_0810.jpg',
      'assets/test_images/Mikania_micrantha/IMG_1399.jpg',
      'assets/test_images/Mikania_micrantha/IMG_1402.jpg',
      'assets/test_images/Mikania_micrantha/IMG_1407.jpg',
      'assets/test_images/Mikania_micrantha/IMG_1408.jpg',
      'assets/test_images/Mikania_micrantha/IMG_1461.jpg',
      'assets/test_images/Mikania_micrantha/IMG_1463.jpg',
      'assets/test_images/Mikania_micrantha/IMG_1464.jpg',
      'assets/test_images/Mikania_micrantha/IMG_1465.jpg',
      'assets/test_images/Mikania_micrantha/IMG_1466.jpg',
      'assets/test_images/Mikania_micrantha/IMG_1467.jpg',
      'assets/test_images/Mikania_micrantha/IMG_1468.jpg',
      'assets/test_images/Mikania_micrantha/IMG_1470.jpg',
      'assets/test_images/Mikania_micrantha/IMG_1477.jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (54).jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (55).jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (56).jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (57).jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (58).jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (59).jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (60).jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (61).jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (62).jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (63).jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (64).jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (65).jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (66).jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (67).jpg',
      'assets/test_images/Mikania_micrantha/Mikania Micrantha (68).jpg',
    ],
    'Moringa_oleifera': [
      'assets/test_images/Moringa_oleifera/124_Moringa oleifera.jpg',
    ],
  };

  static String getDisplayName(String plantId) => displayNames[plantId] ?? plantId;

  static List<String> getImages(String plantId) => images[plantId] ?? [];

  static int getImageCount(String plantId) => images[plantId]?.length ?? 0;
}

// Legacy: for backward compatibility with test_image_gallery.dart
final Map<String, List<String>> testPlantImages = PlantAssets.images;